"""Build the derived half of the site from the day entries.

Day files under `log/` are the only thing written by hand. Everything else — the
sky data the month map is drawn from, the constellation pages, the time tables,
the running totals — is regenerated from their frontmatter by this script. Run it
before `quarto render`:

    python scripts/build.py

It also hydrates regions it owns inside each day file: a few frontmatter keys,
the planet element at the top, and the time table between the `odaily:time`
markers. Everything else in the file is left exactly as written.
"""

from __future__ import annotations

import json
import math
import re
import shutil
import sys
from collections import defaultdict
from datetime import date, timedelta
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
LOG_DIR = ROOT / "log"
ASSET_DIR = ROOT / "assets"
PROJECT_DIR = ROOT / "projects"
SYSTEM_DIR = ROOT / "system"
SKY_DIR = ROOT / "sky"
YEAR_DIR = ROOT / "galaxy"
INCLUDE_DIR = ROOT / "_includes"

FM_RE = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n?", re.DOTALL)
TIME_BEGIN = "<!-- odaily:time:begin -->"
TIME_END = "<!-- odaily:time:end -->"
PLANET_BEGIN = "<!-- odaily:planet:begin -->"
PLANET_END = "<!-- odaily:planet:end -->"
GENERATED_BANNER = "<!-- Generated by scripts/build.py — edits here are overwritten. -->"

MONTHS = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
]

# What a day is made of. The map turns the dominant category of a day's hours
# into the planet's surface, which is the whole reason categories exist.
CATEGORY_TYPE = {
    "writing": "ice",
    "reading": "forest",
    "coding": "gas",
    "data": "ocean",
    "meeting": "lava",
    "admin": "rock",
}

# The heading whose emptiness decides whether the day gets a comet.
IDEA_HEADING = "An idea that came up"

# Stellar systems are custom day-ranges, not necessarily whole months — once a
# system runs out of things to name (the last planet of the Solar System, say)
# a new one can start mid-month with its own name and its own ring of weeks.
# A day not covered by any range here falls back to its own calendar month,
# unnamed (the map then shows "Month Year", as it always used to).
SYSTEM_RANGES = [
    {"key": "2026-08-solar", "name": "Solar System",
     "start": date(2026, 8, 4), "end": date(2026, 8, 16)},
    {"key": "2026-08-alpha-centauri", "name": "Alpha Centauri",
     "start": date(2026, 8, 17), "end": date(2026, 8, 31)},
]


def system_for(day: date) -> dict:
    """Which stellar system a day belongs to: an explicit range if one covers
    it, else the whole calendar month it falls in."""
    for rng in SYSTEM_RANGES:
        if rng["start"] <= day <= rng["end"]:
            return rng
    first = day.replace(day=1)
    next_month = date(day.year + (day.month == 12), day.month % 12 + 1, 1)
    return {
        "key": f"{day.year}-{day.month:02d}",
        "name": "",
        "start": first,
        "end": next_month - timedelta(days=1),
    }

# Assigned in order to any project that does not name its own colour. Chosen to
# stay distinguishable from each other once two or three of them are blended.
HOUSE_COLORS = [
    "#4fc3f7", "#f2a65a", "#8ad17f", "#c792ea", "#ef7a85",
    "#6ee7d0", "#ffd166", "#9aa7ff", "#f78fb3", "#8fd3c7",
]

# Every day is named after something real. Deterministic from the date, so a day
# keeps its name forever — and looking one up is its own small reward.
SKY_NAMES = [
    "Vega", "Altair", "Rigel", "Betelgeuse", "Sirius", "Procyon", "Capella",
    "Arcturus", "Aldebaran", "Antares", "Spica", "Deneb", "Fomalhaut", "Pollux",
    "Regulus", "Castor", "Bellatrix", "Mizar", "Alcor", "Polaris", "Canopus",
    "Achernar", "Hadar", "Acrux", "Gacrux", "Shaula", "Nunki", "Alnilam",
    "Alnitak", "Mintaka", "Saiph", "Rasalhague", "Eltanin", "Kochab", "Merak",
    "Dubhe", "Phecda", "Megrez", "Alioth", "Alkaid", "Thuban", "Algol",
    "Almach", "Mirach", "Alpheratz", "Hamal", "Menkar", "Mira", "Denebola",
    "Zosma", "Alphard", "Avior", "Miaplacidus", "Atria", "Peacock", "Alnair",
    "Diphda", "Ankaa", "Sadalsuud", "Sadalmelik", "Enif", "Markab", "Scheat",
    "Algenib", "Matar", "Homam", "Sheratan", "Mesarthim", "Zubeneschamali",
    "Zubenelgenubi", "Unukalhai", "Sabik", "Kaus Australis", "Ascella",
    "Albaldah", "Dabih", "Deneb Algedi", "Nashira", "Skat", "Alrescha",
    "Kepler-186f", "Kepler-442b", "Kepler-452b", "TRAPPIST-1e", "Proxima b",
    "Gliese 581g", "HD 209458 b", "55 Cancri e", "WASP-12b", "Kepler-22b",
    "LHS 1140 b", "TOI-700 d", "K2-18b", "GJ 1214 b", "HR 8799 e",
    "Titan", "Europa", "Ganymede", "Callisto", "Io", "Enceladus", "Mimas",
    "Triton", "Charon", "Miranda", "Ariel", "Umbriel", "Titania", "Oberon",
    "Iapetus", "Rhea", "Dione", "Tethys", "Phobos", "Deimos", "Amalthea",
    "Ceres", "Vesta", "Pallas", "Hygiea", "Eris", "Makemake", "Haumea",
    "Sedna", "Quaoar", "Orcus", "Ixion", "Varuna", "Arrokoth", "Chiron",
]


class BuildError(Exception):
    pass


def fmt_hours(h: float) -> str:
    total = int(round(h * 60))
    hours, mins = divmod(total, 60)
    if hours and mins:
        return f"{hours}h {mins:02d}m"
    if hours:
        return f"{hours}h"
    return f"{mins}m"


def yaml_str(value) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def seed_for(day: date) -> int:
    """Must match the seed the map computes, or an entry's planet would not be
    the one the map showed."""
    return day.year * 10000 + day.month * 100 + day.day


def sky_name(day: date) -> str:
    # Spread by a prime so consecutive days never land on neighbouring names.
    return SKY_NAMES[(seed_for(day) * 7919) % len(SKY_NAMES)]


def hex_to_rgb(value: str) -> tuple[float, float, float]:
    value = value.lstrip("#")
    return tuple(int(value[i:i + 2], 16) for i in (0, 2, 4))


def blend_colors(weighted: list[tuple[str, float]]) -> str:
    """Mix project colours in proportion to hours.

    Averaged in linear light rather than straight sRGB: mixing #ff0000 and
    #00ff00 the naive way gives a muddy olive, which would make every split day
    look like the same brown."""
    if not weighted:
        return "#7d8aa8"
    total = sum(w for _, w in weighted) or float(len(weighted))
    r = g = b = 0.0
    for colour, weight in weighted:
        share = (weight / total) if total else 1 / len(weighted)
        cr, cg, cb = hex_to_rgb(colour)
        r += (cr / 255) ** 2.2 * share
        g += (cg / 255) ** 2.2 * share
        b += (cb / 255) ** 2.2 * share
    out = [round(255 * max(0.0, min(1.0, c)) ** (1 / 2.2)) for c in (r, g, b)]
    return "#%02x%02x%02x" % tuple(out)


def day_color(day: dict, projects: dict) -> str:
    per: dict[str, float] = defaultdict(float)
    for session in day["sessions"]:
        per[session["project"]] += session["hours"]
    # A day with an entry but no hours still has projects; weight them equally.
    if per and not any(per.values()):
        per = {slug: 1.0 for slug in per}
    return blend_colors([(projects[s]["color"], h) for s, h in per.items()])


# --------------------------------------------------------------------------
# Reading
# --------------------------------------------------------------------------

def load_registry() -> tuple[dict, dict]:
    data = yaml.safe_load((ROOT / "projects.yml").read_text(encoding="utf-8")) or {}
    projects = data.get("projects") or {}
    groups = data.get("groups") or {}
    for i, (slug, meta) in enumerate(sorted(projects.items())):
        colour = str(meta.get("color") or "").strip()
        if not re.fullmatch(r"#[0-9a-fA-F]{6}", colour):
            if colour:
                raise BuildError(
                    f"projects.yml: project '{slug}' has colour '{colour}' — "
                    f"use a six-digit hex like \"#4fc3f7\""
                )
            colour = HOUSE_COLORS[i % len(HOUSE_COLORS)]
        meta["color"] = colour.lower()
    for slug, meta in projects.items():
        group = meta.get("group")
        if group and group not in groups:
            raise BuildError(f"projects.yml: project '{slug}' is in unknown group '{group}'")
        category = meta.get("category")
        if category and category not in CATEGORY_TYPE:
            raise BuildError(
                f"projects.yml: project '{slug}' has unknown category '{category}' "
                f"— use one of {', '.join(CATEGORY_TYPE)}"
            )
    return projects, groups


def split_frontmatter(text: str) -> tuple[str, dict, str]:
    match = FM_RE.match(text)
    if not match:
        raise BuildError("file has no YAML frontmatter block")
    return match.group(1), yaml.safe_load(match.group(1)) or {}, text[match.end():]


def idea_text(body: str) -> str:
    """Whatever was written under the idea heading, comments stripped out."""
    match = re.search(
        rf"^##\s+{re.escape(IDEA_HEADING)}\s*$(.*?)(?=^##\s|\Z)",
        body, re.MULTILINE | re.DOTALL,
    )
    if not match:
        return ""
    text = re.sub(r"<!--.*?-->", "", match.group(1), flags=re.DOTALL)
    text = re.sub(r"^:::.*$", "", text, flags=re.MULTILINE)
    return " ".join(text.split())


def has_idea(body: str) -> bool:
    return bool(idea_text(body))


def read_days(projects: dict) -> list[dict]:
    days, problems = [], []
    for path in sorted(LOG_DIR.glob("*.qmd")):
        if path.name.startswith("_"):
            continue
        try:
            fm_text, fm, body = split_frontmatter(path.read_text(encoding="utf-8"))
        except BuildError as exc:
            problems.append(f"{path.name}: {exc}")
            continue

        try:
            day = date.fromisoformat(path.stem)
        except ValueError:
            problems.append(f"{path.name}: filename must be an ISO date, e.g. 2026-07-31.qmd")
            continue

        declared = fm.get("date")
        if isinstance(declared, date) and declared != day:
            problems.append(f"{path.name}: frontmatter date {declared} does not match the filename")

        sessions = fm.get("sessions") or []
        if not isinstance(sessions, list):
            problems.append(f"{path.name}: `sessions` must be a list")
            sessions = []

        clean = []
        for i, session in enumerate(sessions, 1):
            if not isinstance(session, dict):
                problems.append(f"{path.name}: session {i} must be a mapping")
                continue
            slug = session.get("project")
            if slug not in projects:
                problems.append(
                    f"{path.name}: session {i} refers to unknown project '{slug}' "
                    f"— add it to projects.yml"
                )
                continue
            try:
                hours = float(session.get("hours", 0) or 0)
            except (TypeError, ValueError):
                problems.append(f"{path.name}: session {i} has non-numeric hours")
                continue
            if hours < 0:
                problems.append(f"{path.name}: session {i} has negative hours")
                continue
            category = session.get("category") or projects[slug].get("category") or "admin"
            if category not in CATEGORY_TYPE:
                problems.append(
                    f"{path.name}: session {i} has unknown category '{category}' "
                    f"— use one of {', '.join(CATEGORY_TYPE)}"
                )
                continue
            clean.append({
                "project": slug, "hours": hours,
                "note": session.get("note"), "category": category,
            })

        days.append({
            "path": path,
            "date": day,
            "fm_text": fm_text,
            "fm": fm,
            "body": body,
            "sessions": clean,
            "hours": round(sum(s["hours"] for s in clean), 2),
            "demo": bool(fm.get("demo")),
            "milestone": bool(fm.get("milestone")),
            "idea": has_idea(body),
            "idea_text": idea_text(body),
            "title": fm.get("title") or day.isoformat(),
        })

    if problems:
        raise BuildError("\n".join("  - " + p for p in problems))
    return days


def dominant_type(day: dict) -> str:
    """The surface is whichever kind of work took the most of the day."""
    tally: dict[str, float] = defaultdict(float)
    for session in day["sessions"]:
        tally[session["category"]] += session["hours"]
    if not tally:
        return "rock"
    # Ties break alphabetically so the sprite never flickers between builds.
    best = max(sorted(tally), key=lambda c: tally[c])
    return CATEGORY_TYPE[best]


# --------------------------------------------------------------------------
# Hydrating the day files
# --------------------------------------------------------------------------

def set_key(fm_lines: list[str], key: str, value: str) -> bool:
    """Replace or append a top-level scalar key. Nested session lines are
    indented, so matching on a column-zero key never touches them."""
    line = f"{key}: {value}"
    pattern = re.compile(rf"^{re.escape(key)}\s*:")
    for i, existing in enumerate(fm_lines):
        if pattern.match(existing):
            if existing.rstrip() == line:
                return False
            fm_lines[i] = line
            return True
    fm_lines.append(line)
    return True


def replace_region(body: str, begin: str, end: str, block: str) -> tuple[str, bool]:
    if begin not in body or end not in body:
        return body, False
    new = re.sub(
        re.escape(begin) + r".*?" + re.escape(end),
        lambda _: f"{begin}\n{block}\n{end}",
        body, flags=re.DOTALL,
    )
    return new, new != body


def time_table(day: dict, projects: dict, prefix: str = "../") -> str:
    if not day["sessions"]:
        return "_No time logged for this day._"

    per_project: dict[str, float] = defaultdict(float)
    notes: list[tuple[str, str]] = []
    for session in day["sessions"]:
        per_project[session["project"]] += session["hours"]
        if session.get("note"):
            notes.append((session["project"], str(session["note"])))

    rows = ["| Constellation | Kind | Time |", "|:--|:--|--:|"]
    for slug, hours in sorted(per_project.items(), key=lambda kv: (-kv[1], kv[0])):
        kinds = sorted({s["category"] for s in day["sessions"] if s["project"] == slug})
        name = projects[slug].get("name", slug)
        rows.append(f"| [{name}]({prefix}projects/{slug}.qmd) | {', '.join(kinds)} | {fmt_hours(hours)} |")
    rows.append(f"| **Total** | | **{fmt_hours(day['hours'])}** |")

    out = "\n".join(rows)
    if notes:
        out += "\n\n" + "\n".join(
            f"- **{projects[slug].get('name', slug)}** — {note}" for slug, note in notes
        )
    return out


def planet_name_for(day: dict) -> str:
    """A day's own `planet_name:` wins; otherwise the seeded catalogue name."""
    return day["fm"].get("planet_name") or sky_name(day["date"])


def planet_color_for(day: dict, projects: dict) -> str:
    """A day's own `planet_color:` wins; otherwise the projects' blend."""
    return day["fm"].get("planet_color") or day_color(day, projects)


def planet_orbit_au_for(day: dict) -> float | None:
    """A day's own `planet_orbit_au:` — a real (or invented) distance from its
    system's star, in whatever unit that system uses. None if the day is an
    ordinary logged day rather than a named body."""
    v = day["fm"].get("planet_orbit_au")
    return float(v) if v is not None else None


def planet_block(day: dict, projects: dict) -> str:
    # Sorted the same way the map sorts them, so a day's moons are the same
    # projects in the same order in both places.
    slugs = sorted({s["project"] for s in day["sessions"]})
    moon_colors = [projects[s]["color"] for s in slugs[1:]]
    name = planet_name_for(day)
    color = planet_color_for(day, projects)
    return (
        '<canvas class="day-planet" width="112" height="112" role="img" '
        f'aria-label="The planet for {day["date"].isoformat()}" '
        f'data-seed="{seed_for(day["date"])}" '
        f'data-type="{dominant_type(day)}" '
        f'data-color="{color}" '
        f'data-moons="{len(moon_colors)}" '
        f'data-moon-colors="{",".join(moon_colors)}" '
        f'data-milestone="{str(day["milestone"]).lower()}" '
        f'data-idea="{str(day["idea"]).lower()}"></canvas>\n'
        f'<p class="day-name">{name}</p>'
    )


def hydrate_day(day: dict, projects: dict) -> bool:
    fm_lines = day["fm_text"].split("\n")
    changed = False
    categories = sorted({s["project"] for s in day["sessions"]})

    changed |= set_key(fm_lines, "system", yaml_str(day["date"].strftime("%Y-%m")))
    changed |= set_key(fm_lines, "hours", str(day["hours"]))
    changed |= set_key(fm_lines, "categories", "[" + ", ".join(categories) + "]")

    body = day["body"]
    body, hit = replace_region(body, TIME_BEGIN, TIME_END, time_table(day, projects))
    changed |= hit
    if TIME_BEGIN not in day["body"]:
        print(f"  ! {day['path'].name}: no odaily:time markers, time table not written")

    body, hit = replace_region(body, PLANET_BEGIN, PLANET_END, planet_block(day, projects))
    changed |= hit
    if PLANET_BEGIN not in day["body"]:
        print(f"  ! {day['path'].name}: no odaily:planet markers, sprite not written")

    if changed:
        day["path"].write_text(
            "---\n" + "\n".join(fm_lines) + "\n---\n" + body, encoding="utf-8"
        )
    return changed


# --------------------------------------------------------------------------
# Generating
# --------------------------------------------------------------------------

def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def sky_data(days: list[dict], projects: dict, groups: dict) -> str:
    """Everything the map needs, newest system first."""
    systems: dict[str, dict] = {}
    for day in days:
        rng = system_for(day["date"])
        system = systems.setdefault(rng["key"], {
            "key": rng["key"],
            "name": rng["name"],
            "start": rng["start"],
            "end": rng["end"],
            "days": {},
        })
        system["days"][day["date"].isoformat()] = {
            "hours": round(day["hours"], 2),
            "type": dominant_type(day),
            "color": planet_color_for(day, projects),
            "name": planet_name_for(day),
            "orbitAu": planet_orbit_au_for(day),
            "projects": sorted({s["project"] for s in day["sessions"]}),
            "milestone": day["milestone"],
            "idea": day["idea"],
            "title": day["title"],
            "url": f"log/{day['date'].isoformat()}.html",
            "sessions": [
                [projects[s["project"]].get("name", s["project"]), s["hours"], s.get("note") or ""]
                for s in day["sessions"]
            ],
        }

    # A day with a real `planet_orbit_au` sits at its own distance from the
    # sun rather than on the ring its calendar week happens to land on — that
    # is what makes Mercury sit near the sun and Eris sit at the outer edge
    # regardless of which week either falls in. Distances are compressed with
    # log10 (Eris is 170x further out than Mercury) and normalised against
    # only the other named bodies in the *same* system, so every system's
    # bodies use the full width of the ring band no matter its own scale.
    for system in systems.values():
        aus = [d["orbitAu"] for d in system["days"].values() if d["orbitAu"] is not None]
        if not aus:
            continue
        logs = [math.log10(au) for au in aus]
        lo, hi = min(logs), max(logs)
        for d in system["days"].values():
            if d["orbitAu"] is None:
                d["orbit"] = None
            elif hi == lo:
                d["orbit"] = 0.5
            else:
                d["orbit"] = (math.log10(d["orbitAu"]) - lo) / (hi - lo)

    # What each constellation amounts to, so the map can introduce one without
    # fetching its page. Totals are derived here rather than in the browser
    # because the browser only ever sees the days, never the sessions' shape.
    tally: dict[str, dict] = {}
    for day in days:
        for session in day["sessions"]:
            slug = session["project"]
            item = tally.setdefault(slug, {"days": set(), "hours": 0.0})
            item["days"].add(day["date"])
            item["hours"] += session["hours"]

    return json.dumps({
        "projects": {
            slug: {
                "name": meta.get("name", slug),
                "group": groups.get(meta.get("group"), {}).get("name", ""),
                "color": meta["color"],
                "blurb": meta.get("blurb", ""),
                "category": meta.get("category", ""),
                "status": meta.get("status", ""),
                "url": f"projects/{slug}.html",
                "days": len(tally.get(slug, {}).get("days") or ()),
                "hours": round(tally.get(slug, {}).get("hours", 0.0), 2),
                "first": min(tally[slug]["days"]).isoformat() if slug in tally else "",
                "last": max(tally[slug]["days"]).isoformat() if slug in tally else "",
            }
            for slug, meta in projects.items()
        },
        "systems": [
            {**s, "start": s["start"].isoformat(), "end": s["end"].isoformat()}
            for s in sorted(systems.values(), key=lambda s: s["start"], reverse=True)
        ],
    }, indent=1)


def streak(days: list[dict], today: date) -> int:
    logged = {d["date"] for d in days}
    # A streak that ended yesterday still counts today until the day is over.
    cursor = today if today in logged else today - timedelta(days=1)
    count = 0
    while cursor in logged:
        count += 1
        cursor -= timedelta(days=1)
    return count


def summary_include(days: list[dict], today: date) -> str:
    total = sum(d["hours"] for d in days)
    return "\n".join([
        GENERATED_BANNER,
        "",
        '<div class="stat-row">',
        f'<div class="stat"><span class="stat-value">{len(days)}</span>'
        f'<span class="stat-label">planets charted</span></div>',
        f'<div class="stat"><span class="stat-value">{fmt_hours(total) if total else "0h"}</span>'
        f'<span class="stat-label">time logged</span></div>',
        f'<div class="stat"><span class="stat-value">{streak(days, today)}</span>'
        f'<span class="stat-label">day streak</span></div>',
        "</div>",
        "",
    ])


def archive_include(days: list[dict]) -> str:
    """A plain list of every entry. It is the fallback when the canvas cannot
    run, and it is what the site search actually indexes."""
    out = [GENERATED_BANNER, ""]
    by_system: dict[tuple[int, int], list[dict]] = defaultdict(list)
    for day in days:
        by_system[(day["date"].year, day["date"].month)].append(day)

    for (year, month), system_days in sorted(by_system.items(), reverse=True):
        hours = sum(d["hours"] for d in system_days)
        out.append(f"### [{MONTHS[month - 1]} {year}](system/{year}-{month:02d}.qmd)")
        out.append("")
        out.append(f"{len(system_days)} days · {fmt_hours(hours)} · "
                   f"[the {year} galaxy](galaxy/{year}.qmd)")
        out.append("")
        for day in sorted(system_days, key=lambda d: d["date"], reverse=True):
            iso = day["date"].isoformat()
            marks = ("  ✦" if day["milestone"] else "") + ("  ☄" if day["idea"] else "")
            out.append(f"- [{day['title']}](log/{iso}.qmd) — {fmt_hours(day['hours'])}{marks}")
        out.append("")
    return "\n".join(out) + "\n"


def list_include(days: list[dict], projects: dict) -> str:
    """The other view of the same collection.

    A universe is for browsing and thinking; this is for finding what you did on
    12 March. The failure mode of a metaphor site is being delightful for thirty
    seconds and useless for the daily task, and you are the daily user."""
    head = [
        GENERATED_BANNER,
        "",
        '<table class="log-table" id="log-table">',
        "<thead><tr>"
        '<th data-sort="date" aria-sort="descending">Date</th>'
        '<th data-sort="name">Name</th>'
        '<th data-sort="hours" class="num">Hours</th>'
        '<th data-sort="kind">Kind</th>'
        '<th data-sort="projects">Constellations</th>'
        '<th data-sort="marks">·</th>'
        "</tr></thead>",
        "<tbody>",
    ]
    rows = []
    for day in reversed(days):
        iso = day["date"].isoformat()
        kinds = ", ".join(sorted({s["category"] for s in day["sessions"]})) or "—"
        slugs = sorted({s["project"] for s in day["sessions"]})
        names = ", ".join(projects[s].get("name", s) for s in slugs) or "—"
        swatches = "".join(
            f'<i class="swatch" style="background:{projects[s]["color"]}"></i>' for s in slugs
        )
        marks = ("✦" if day["milestone"] else "") + ("☄" if day["idea"] else "")
        rows.append(
            f'<tr data-date="{iso}" data-hours="{day["hours"]}">'
            f'<td><a href="log/{iso}.html">{iso}</a></td>'
            f'<td class="dim">{sky_name(day["date"])}</td>'
            f'<td class="num">{fmt_hours(day["hours"]) if day["hours"] else "—"}</td>'
            f"<td>{kinds}</td>"
            f'<td>{swatches}{names}</td>'
            f'<td class="marks">{marks or ""}</td>'
            f"</tr>"
        )
    if not rows:
        rows.append('<tr><td colspan="6" class="dim">Nothing logged yet.</td></tr>')
    return "\n".join(head + rows + ["</tbody>", "</table>", ""]) + "\n"


def project_page(slug: str, meta: dict, groups: dict, days: list[dict]) -> str:
    mine = [d for d in days if any(s["project"] == slug for s in d["sessions"])]
    hours = sum(s["hours"] for d in mine for s in d["sessions"] if s["project"] == slug)
    group = groups.get(meta.get("group"), {})

    out = [
        "---",
        f"title: {yaml_str(meta.get('name', slug))}",
        f"subtitle: {yaml_str('Constellation in ' + group.get('name', 'the field'))}",
        "---",
        "",
        GENERATED_BANNER,
        "",
    ]
    if meta.get("blurb"):
        out.append(f"{meta['blurb']}\n")

    if not mine:
        out.append("_No days logged against this constellation yet._")
        return "\n".join(out) + "\n"

    out.append(
        f'<div class="stat-row">'
        f'<div class="stat"><span class="stat-value">{fmt_hours(hours)}</span>'
        f'<span class="stat-label">total time</span></div>'
        f'<div class="stat"><span class="stat-value">{len(mine)}</span>'
        f'<span class="stat-label">days visited</span></div>'
        f'<div class="stat"><span class="stat-value">{mine[0]["date"].isoformat()}</span>'
        f'<span class="stat-label">first seen</span></div>'
        f"</div>\n"
    )
    out.append("| Day | Kind | Time | Note |")
    out.append("|:--|:--|--:|:--|")
    for day in reversed(mine):
        iso = day["date"].isoformat()
        mine_sessions = [s for s in day["sessions"] if s["project"] == slug]
        day_hours = sum(s["hours"] for s in mine_sessions)
        kinds = ", ".join(sorted({s["category"] for s in mine_sessions}))
        notes = " ".join(str(s["note"]) for s in mine_sessions if s.get("note"))
        out.append(f"| [{iso}](../log/{iso}.qmd) | {kinds} | {fmt_hours(day_hours)} | {notes or '—'} |")
    return "\n".join(out) + "\n"


def projects_index(projects: dict, groups: dict, days: list[dict]) -> str:
    hours: dict[str, float] = defaultdict(float)
    seen: dict[str, set] = defaultdict(set)
    for day in days:
        for session in day["sessions"]:
            hours[session["project"]] += session["hours"]
            seen[session["project"]].add(day["date"])

    out = [
        "---",
        'title: "Constellations"',
        'subtitle: "The same days, read along the other axis."',
        "---",
        "",
        GENERATED_BANNER,
        "",
        "A day is a planet and a month is a system, but a project is a *constellation*:",
        "a pattern drawn across whatever nights it happened to appear in. Pick one on the",
        "[galaxy](../index.qmd) map to see it traced across a month.",
        "",
    ]

    ungrouped = [s for s in projects if projects[s].get("group") not in groups]
    for group_key, group in list(groups.items()) + [(None, {"name": "Unfiled"})]:
        members = (
            ungrouped if group_key is None
            else [s for s in projects if projects[s].get("group") == group_key]
        )
        if not members:
            continue
        heading = group.get("name", group_key)
        out.append(f"## [{heading}](../sky/{group_key}.qmd)\n" if group_key else f"## {heading}\n")
        if group.get("blurb"):
            out.append(f"{group['blurb']}\n")
        out.append("| Constellation | Usually | Time | Days | Status |")
        out.append("|:--|:--|--:|--:|:--|")
        for slug in sorted(members, key=lambda s: (-hours[s], s)):
            meta = projects[slug]
            out.append(
                f"| [{meta.get('name', slug)}]({slug}.qmd) "
                f"| {meta.get('category', '—')} "
                f"| {fmt_hours(hours[slug]) if hours[slug] else '—'} "
                f"| {len(seen[slug]) or '—'} "
                f"| {meta.get('status', '—')} |"
            )
        out.append("")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------
# The other axes: a month, a year, a family of constellations, the comets.
# The day files already carry all of this; these pages only re-read them along
# a different axis.
# --------------------------------------------------------------------------

def system_page(year: int, month: int, days: list[dict], projects: dict) -> str:
    mine = [d for d in days if d["date"].year == year and d["date"].month == month]
    hours = sum(d["hours"] for d in mine)
    label = f"{MONTHS[month - 1]} {year}"

    out = [
        "---",
        f"title: {yaml_str(label)}",
        'subtitle: "Stellar system"',
        "---",
        "",
        GENERATED_BANNER,
        "",
        f'<div class="stat-row">'
        f'<div class="stat"><span class="stat-value">{len(mine)}</span>'
        f'<span class="stat-label">planets</span></div>'
        f'<div class="stat"><span class="stat-value">{fmt_hours(hours) if hours else "0h"}</span>'
        f'<span class="stat-label">time logged</span></div>'
        f"</div>\n",
        "| Day | Time | Constellations |",
        "|:--|--:|:--|",
    ]
    for day in mine:
        iso = day["date"].isoformat()
        names = ", ".join(
            projects[s].get("name", s) for s in sorted({x["project"] for x in day["sessions"]})
        )
        marks = (" ✦" if day["milestone"] else "") + (" ☄" if day["idea"] else "")
        out.append(f"| [{day['date'].strftime('%a %d')}](../log/{iso}.qmd){marks} "
                   f"| {fmt_hours(day['hours'])} | {names or '—'} |")
    if not mine:
        out.append("| — | — | — |")
    out.append("")
    out.append("[← the whole galaxy](../index.qmd)")
    return "\n".join(out) + "\n"


def galaxy_page(year: int, days: list[dict]) -> str:
    mine = [d for d in days if d["date"].year == year]
    by_month: dict[int, list[dict]] = defaultdict(list)
    for day in mine:
        by_month[day["date"].month].append(day)

    out = [
        "---",
        f'title: "{year}"',
        'subtitle: "Galaxy"',
        "---",
        "",
        GENERATED_BANNER,
        "",
        f'<div class="stat-row">'
        f'<div class="stat"><span class="stat-value">{len(mine)}</span>'
        f'<span class="stat-label">days logged</span></div>'
        f'<div class="stat"><span class="stat-value">{fmt_hours(sum(d["hours"] for d in mine))}</span>'
        f'<span class="stat-label">time logged</span></div>'
        f'<div class="stat"><span class="stat-value">{len(by_month)}</span>'
        f'<span class="stat-label">systems</span></div>'
        f"</div>\n",
        "| System | Days | Time |",
        "|:--|--:|--:|",
    ]
    for month in sorted(by_month):
        group = by_month[month]
        out.append(f"| [{MONTHS[month - 1]}](../system/{year}-{month:02d}.qmd) "
                   f"| {len(group)} | {fmt_hours(sum(d['hours'] for d in group))} |")
    return "\n".join(out) + "\n"


def sky_page(group_key: str, group: dict, projects: dict, days: list[dict]) -> str:
    members = [s for s in projects if projects[s].get("group") == group_key]
    hours: dict[str, float] = defaultdict(float)
    seen: dict[str, set] = defaultdict(set)
    for day in days:
        for session in day["sessions"]:
            if session["project"] in members:
                hours[session["project"]] += session["hours"]
                seen[session["project"]].add(day["date"])

    total = sum(hours.values())
    covered = set().union(*seen.values()) if seen else set()

    out = [
        "---",
        f"title: {yaml_str(group.get('name', group_key))}",
        'subtitle: "Constellation family"',
        "---",
        "",
        GENERATED_BANNER,
        "",
    ]
    if group.get("blurb"):
        out.append(group["blurb"] + "\n")
    out.append(
        f'<div class="stat-row">'
        f'<div class="stat"><span class="stat-value">{fmt_hours(total) if total else "0h"}</span>'
        f'<span class="stat-label">total time</span></div>'
        f'<div class="stat"><span class="stat-value">{len(covered)}</span>'
        f'<span class="stat-label">days touched</span></div>'
        f'<div class="stat"><span class="stat-value">{len(members)}</span>'
        f'<span class="stat-label">constellations</span></div>'
        f"</div>\n"
    )
    out.append("| Constellation | Time | Days | Status |")
    out.append("|:--|--:|--:|:--|")
    for slug in sorted(members, key=lambda s: (-hours[s], s)):
        meta = projects[slug]
        out.append(f"| [{meta.get('name', slug)}](../projects/{slug}.qmd) "
                   f"| {fmt_hours(hours[slug]) if hours[slug] else '—'} "
                   f"| {len(seen[slug]) or '—'} | {meta.get('status', '—')} |")
    return "\n".join(out) + "\n"


def comets_page(days: list[dict]) -> str:
    """Ideas are comets: they arrive on their own schedule and are gone by
    morning unless written down. This is the page that makes writing them pay."""
    with_ideas = [d for d in days if d["idea_text"]]
    out = [
        "---",
        'title: "Comets"',
        'subtitle: "Every idea that came up, and the day it passed through."',
        "---",
        "",
        GENERATED_BANNER,
        "",
    ]
    if not with_ideas:
        out.append("_No ideas recorded yet. Write anything under "
                   "**An idea that came up** in a day's entry and it appears here._")
        return "\n".join(out) + "\n"

    out.append(
        f'<div class="stat-row">'
        f'<div class="stat"><span class="stat-value">{len(with_ideas)}</span>'
        f'<span class="stat-label">comets logged</span></div>'
        f'<div class="stat"><span class="stat-value">'
        f'{round(100 * len(with_ideas) / max(1, len(days)))}%</span>'
        f'<span class="stat-label">of days had one</span></div>'
        f"</div>\n"
    )
    for day in reversed(with_ideas):
        iso = day["date"].isoformat()
        out.append(f"### [{day['title']}](log/{iso}.qmd)\n")
        out.append(day["idea_text"] + "\n")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------

def main() -> int:
    try:
        projects, groups = load_registry()
        LOG_DIR.mkdir(exist_ok=True)
        days = read_days(projects)
    except BuildError as exc:
        print("Build failed:\n" + str(exc), file=sys.stderr)
        return 1

    days.sort(key=lambda d: d["date"])
    print(f"Read {len(days)} day entries, {len(projects)} projects.")

    touched = sum(hydrate_day(day, projects) for day in days)
    print(f"Day files: {touched} hydrated.")

    write_if_changed(ASSET_DIR / "sky.json", sky_data(days, projects, groups))
    write_if_changed(INCLUDE_DIR / "summary.md", summary_include(days, date.today()))
    write_if_changed(INCLUDE_DIR / "archive.md", archive_include(days))
    write_if_changed(INCLUDE_DIR / "list.md", list_include(days, projects))

    if PROJECT_DIR.exists():
        shutil.rmtree(PROJECT_DIR)
    for slug, meta in projects.items():
        write_if_changed(PROJECT_DIR / f"{slug}.qmd", project_page(slug, meta, groups, days))
    write_if_changed(PROJECT_DIR / "index.qmd", projects_index(projects, groups, days))
    print(f"Constellations: {len(projects)} pages written.")

    # The same days along their other axes.
    for directory in (SYSTEM_DIR, SKY_DIR, YEAR_DIR):
        if directory.exists():
            shutil.rmtree(directory)

    months = sorted({(d["date"].year, d["date"].month) for d in days})
    for year, month in months:
        write_if_changed(SYSTEM_DIR / f"{year}-{month:02d}.qmd",
                         system_page(year, month, days, projects))
    for year in sorted({d["date"].year for d in days}):
        write_if_changed(YEAR_DIR / f"{year}.qmd", galaxy_page(year, days))
    for group_key, group in groups.items():
        write_if_changed(SKY_DIR / f"{group_key}.qmd", sky_page(group_key, group, projects, days))
    write_if_changed(ROOT / "comets.qmd", comets_page(days))
    print(f"Systems: {len(months)}, families: {len(groups)}, comets: "
          f"{sum(1 for d in days if d['idea_text'])}.")

    total = sum(d["hours"] for d in days)
    print(f"Total logged: {fmt_hours(total) if total else '0h'}, streak {streak(days, date.today())}.")

    # Loud on purpose: sample days inflate every total on the site, and they are
    # easy to forget about once the galaxy looks nicely full.
    demo = [d for d in days if d["demo"]]
    if demo:
        print(f"\n  NOTE: {len(demo)} of those {len(days)} days are sample data.")
        print("  Remove them with: python scripts/demo.py --clear")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
